server:
  port: 9093

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/UserDB
  jpa:
    hibernate:
      ddl-auto: update

authservice:
  bunu-ben-yazdim:
    secret-key: ${JAVA_SECRETKEY}
    issuer: ${JAVA6_ISSUER}